### ISSUE TITLE
How to enable voting for guest users (not logged).

### ISSUE THREAD

**Issue by brunomonteiro3** [humanmade/comment-popularity#109]
Hello, could you please provide more details on how to enable the voting feature to guest users? I have followed the instructions from the docs, but I may be missing something, since it's not working as expected.

Thanks in advance!

**Comment by swissspidy** [comment]
Installed it on a site today and adding `add_filter( 'hmn_cp_allow_guest_voting', '__return_true' );` to my plugin worked without a problem.

The vote buttons are now displayed for guests too and they can vote as usual.

**Comment by pdewouters** [comment]
thanks @swissspidy for confirming. I did check but forgot to update here.

**Comment by anonimo32** [comment]
I did it creating a new mu-plugin and now I'm getting this error:

Warning: Invalid argument supplied for foreach() in /home/honestin/public_html/wp-content/plugins/comment-popularity/inc/class-comment-popularity.php on line 363

**Comment by swissspidy** [comment]
@anonimo32 I'd suggest opening a new issue for this for visibility

**Comment by anonimo32** [comment]
Done! thank you.
